apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - namespace.yaml
  - role.yaml
  - role-binding.yaml
  - service.yaml
  - service-account.yaml
  - virtual-service.yaml
  - pdb.yaml
