apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: custom-acr
spec:
  encryptedData:
    .dockerconfigjson: {{.Values.imagePullSecret}}
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: custom-acr
    type: kubernetes.io/dockerconfigjson
