apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: azure-storage-account
  namespace: argo
spec:
  encryptedData:
    connection_string: {{.Values.webservice}}
  template:
    metadata:
      creationTimestamp: null
      name: azure-storage-account
      namespace: argo
    type: Opaque
