apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argo-storageaccount
  namespace: argo
spec:
  encryptedData:
    secret: {{.Values.storageAccount.secret}}
  template:
    metadata:
      name: argo-storageaccount
      namespace: {{.Values.namespace}}
    type: Opaque
