apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argo-postgres-config
  namespace: {{.Values.namespace}}
spec:
  encryptedData:
    username: {{.Values.postgres.encryptedUsername}}
    password: {{.Values.postgres.encryptedPassword}}
  template:
    metadata:
      name: argo-postgres-config
      namespace: {{.Values.namespace}}
    type: Opaque
