apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pullsecrets
spec:
  encryptedData:
    .dockerconfigjson: encrypted-data-here
  template:
    metadata:
      creationTimestamp: null
      name: pullsecrets
    type: kubernetes.io/dockerconfigjson
